import React, { useState, useEffect } from 'react'
import { BarChart3, Users, Calendar, TrendingUp, AlertCircle, Activity, Download, Search, Filter, RefreshCw, FileText } from 'lucide-react'
import Card from './Card'
import Button from './Button'

interface DashboardStats {
  total_patients: number
  total_appointments: number
  appointments_today: number
  total_revenue: number
  pending_bills: number
  active_staff: number
}

interface AuditLog {
  id: string
  actor_id?: string
  actor_name?: string
  actor_role?: string
  action: string
  entity_type?: string
  entity_id?: string
  entity_details?: any
  timestamp?: string
  // New fields from centralized logging
  user_id?: string
  user_email?: string
  user_role?: string
  details?: any
  status?: string
  severity?: string
  created_at?: string
}

interface AdminDashboardProps {
  userEmail: string
  userName: string
  userRole: string
  hasViewPermission: boolean
}

const AdminDashboard: React.FC<AdminDashboardProps> = ({
  userEmail,
  userName,
  userRole,
  hasViewPermission
}) => {
  const [stats, setStats] = useState<DashboardStats | null>(null)
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([])
  const [loading, setLoading] = useState(true)
  const [activeTab, setActiveTab] = useState<'overview' | 'audit-logs'>('overview')
  const [searchTerm, setSearchTerm] = useState('')
  const [actionFilter, setActionFilter] = useState('')
  const [severityFilter, setSeverityFilter] = useState('')

  useEffect(() => {
    if (userRole === 'admin') {
      loadDashboardData()
    }
  }, [userRole, activeTab])

  const loadDashboardData = async () => {
    try {
      setLoading(true)
      const token = localStorage.getItem('hp_access_token')
      if (!token) {
        setLoading(false)
        return
      }

      // Load stats
      const statsResponse = await fetch('/api/dashboard/stats', {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      })

      if (statsResponse.ok) {
        const statsData = await statsResponse.json()
        setStats(statsData.data)
      }

      // Load audit logs if on audit tab
      if (activeTab === 'audit-logs') {
        const logsResponse = await fetch('/api/audit-logs?limit=50', {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        })

        if (logsResponse.ok) {
          const logsData = await logsResponse.json()
          setAuditLogs(logsData.data || [])
        }
      }
    } catch (error) {
      console.error('Failed to load dashboard data:', error)
    } finally {
      setLoading(false)
    }
  }

  // Filter audit logs
  const filteredLogs = auditLogs.filter(log => {
    const matchesSearch = searchTerm === '' ||
      (log.action || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
      (log.user_email || log.actor_name || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
      (log.entity_type || '').toLowerCase().includes(searchTerm.toLowerCase())
    const matchesAction = actionFilter === '' || log.action === actionFilter
    const matchesSeverity = severityFilter === '' || (log.details?.severity || log.severity) === severityFilter
    return matchesSearch && matchesAction && matchesSeverity
  })

  // Export to PDF function
  const exportToPDF = () => {
    // Create PDF content
    const pdfContent = `
AUDIT LOG REPORT
================
Generated: ${new Date().toLocaleString()}
Generated By: ${userName} (${userEmail})
Total Records: ${filteredLogs.length}

${'='.repeat(80)}

${filteredLogs.map((log, idx) => `
[${idx + 1}] ${log.action}
    Time: ${new Date(log.created_at || log.timestamp || '').toLocaleString()}
    User: ${log.user_email || log.actor_name || 'System'}
    Role: ${log.user_role || log.actor_role || 'N/A'}
    Severity: ${log.details?.severity || log.severity || 'INFO'}
    Status: ${log.status || 'N/A'}
    Details: ${JSON.stringify(log.details || log.entity_details || {}, null, 2)}
${'─'.repeat(60)}
`).join('\n')}

END OF REPORT
    `.trim()

    // Create blob and download
    const blob = new Blob([pdfContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `audit_logs_${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    alert('Audit logs exported successfully!')
  }

  if (userRole !== 'admin') {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Card className="text-center p-8">
          <AlertCircle size={48} className="mx-auto text-red-400 mb-4" />
          <h2 className="text-xl font-bold text-white mb-2">Access Denied</h2>
          <p className="text-gray-400">Only administrators can access the dashboard</p>
        </Card>
      </div>
    )
  }

  const StatCard = ({ icon: Icon, label, value, color }: any) => (
    <Card className={`border-l-4 ${color}`}>
      <div className="flex items-start justify-between">
        <div>
          <p className="text-gray-400 text-sm mb-1">{label}</p>
          <p className="text-3xl font-bold text-white">{value}</p>
        </div>
        <Icon size={32} className={color.replace('border-', 'text-')} />
      </div>
    </Card>
  )

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold text-white">Admin Dashboard</h2>
        <p className="text-sm text-gray-400">Last updated: {new Date().toLocaleTimeString()}</p>
      </div>

      {/* Tabs */}
      <div className="flex gap-2 border-b border-white/10">
        <button
          onClick={() => {
            setActiveTab('overview')
            loadDashboardData()
          }}
          className={`px-6 py-3 font-semibold text-sm border-b-2 transition ${
            activeTab === 'overview'
              ? 'border-blue-600 text-blue-400'
              : 'border-transparent text-gray-400 hover:text-white'
          }`}
        >
          <BarChart3 size={16} className="inline mr-2" />
          Overview
        </button>
        <button
          onClick={() => {
            setActiveTab('audit-logs')
            loadDashboardData()
          }}
          className={`px-6 py-3 font-semibold text-sm border-b-2 transition ${
            activeTab === 'audit-logs'
              ? 'border-blue-600 text-blue-400'
              : 'border-transparent text-gray-400 hover:text-white'
          }`}
        >
          <Activity size={16} className="inline mr-2" />
          Audit Logs
        </button>
      </div>

      {/* Overview Tab */}
      {activeTab === 'overview' && (
        <>
          {loading ? (
            <Card>
              <p className="text-gray-400">Loading dashboard...</p>
            </Card>
          ) : stats ? (
            <>
              {/* Statistics Cards Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <StatCard
                  icon={Users}
                  label="Total Patients"
                  value={stats.total_patients}
                  color="border-blue-500 text-blue-400"
                />
                <StatCard
                  icon={Calendar}
                  label="Total Appointments"
                  value={stats.total_appointments}
                  color="border-purple-500 text-purple-400"
                />
                <StatCard
                  icon={Calendar}
                  label="Today's Appointments"
                  value={stats.appointments_today}
                  color="border-green-500 text-green-400"
                />
                <StatCard
                  icon={TrendingUp}
                  label="Total Revenue"
                  value={`$${stats.total_revenue.toFixed(2)}`}
                  color="border-yellow-500 text-yellow-400"
                />
                <StatCard
                  icon={AlertCircle}
                  label="Pending Bills"
                  value={stats.pending_bills}
                  color="border-red-500 text-red-400"
                />
                <StatCard
                  icon={Users}
                  label="Active Staff"
                  value={stats.active_staff}
                  color="border-cyan-500 text-cyan-400"
                />
              </div>

              {/* Key Metrics Section */}
              <Card>
                <h3 className="text-lg font-semibold text-white mb-4">Quick Insights</h3>
                <div className="space-y-3">
                  <div className="flex justify-between items-center pb-3 border-b border-white/6">
                    <p className="text-gray-400">Average Patients per Staff</p>
                    <p className="text-lg font-semibold text-white">
                      {stats.active_staff > 0 ? (stats.total_patients / stats.active_staff).toFixed(1) : 0}
                    </p>
                  </div>
                  <div className="flex justify-between items-center pb-3 border-b border-white/6">
                    <p className="text-gray-400">Appointment Utilization Today</p>
                    <p className="text-lg font-semibold text-white">
                      {stats.total_appointments > 0 ? ((stats.appointments_today / stats.total_appointments) * 100).toFixed(1) : 0}%
                    </p>
                  </div>
                  <div className="flex justify-between items-center">
                    <p className="text-gray-400">Pending Bills Amount</p>
                    <p className="text-lg font-semibold text-red-400">
                      {stats.pending_bills} bills pending
                    </p>
                  </div>
                </div>
              </Card>

              {/* System Health */}
              <Card>
                <h3 className="text-lg font-semibold text-white mb-4">System Health</h3>
                <div className="space-y-4">
                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <p className="text-sm text-gray-400">Database Connection</p>
                      <span className="px-2 py-1 bg-green-500/20 text-green-400 text-xs rounded">Active</span>
                    </div>
                    <div className="w-full bg-white/10 rounded-full h-2">
                      <div className="bg-green-500 h-2 rounded-full" style={{ width: '100%' }}></div>
                    </div>
                  </div>
                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <p className="text-sm text-gray-400">API Response Time</p>
                      <span className="px-2 py-1 bg-green-500/20 text-green-400 text-xs rounded">Normal</span>
                    </div>
                    <div className="w-full bg-white/10 rounded-full h-2">
                      <div className="bg-green-500 h-2 rounded-full" style={{ width: '85%' }}></div>
                    </div>
                  </div>
                  <div>
                    <div className="flex justify-between items-center mb-2">
                      <p className="text-sm text-gray-400">Encryption Service</p>
                      <span className="px-2 py-1 bg-green-500/20 text-green-400 text-xs rounded">Running</span>
                    </div>
                    <div className="w-full bg-white/10 rounded-full h-2">
                      <div className="bg-green-500 h-2 rounded-full" style={{ width: '100%' }}></div>
                    </div>
                  </div>
                </div>
              </Card>
            </>
          ) : (
            <Card>
              <p className="text-gray-400">Failed to load dashboard data</p>
            </Card>
          )}
        </>
      )}

      {/* Audit Logs Tab */}
      {activeTab === 'audit-logs' && (
        <div className="space-y-4">
          {/* Search and Filter Bar */}
          <Card>
            <div className="flex flex-wrap gap-4 items-center">
              <div className="flex-1 min-w-[200px]">
                <div className="relative">
                  <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
                  <input
                    type="text"
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    placeholder="Search logs..."
                    className="w-full pl-10 pr-4 py-2 bg-white/5 border border-white/10 rounded text-white placeholder-gray-500 text-sm"
                  />
                </div>
              </div>
              <select
                value={actionFilter}
                onChange={(e) => setActionFilter(e.target.value)}
                className="px-3 py-2 bg-white/5 border border-white/10 rounded text-white text-sm"
              >
                <option value="">All Actions</option>
                <option value="LOGIN_SUCCESS">Login Success</option>
                <option value="LOGIN_FAILED">Login Failed</option>
                <option value="MFA_SUCCESS">MFA Success</option>
                <option value="MFA_FAILED">MFA Failed</option>
                <option value="FILE_ENCRYPTED">File Encrypted</option>
                <option value="FILE_DECRYPTED">File Decrypted</option>
                <option value="DECRYPT_DENIED">Decrypt Denied</option>
                <option value="PERMISSION_DENIED">Permission Denied</option>
              </select>
              <select
                value={severityFilter}
                onChange={(e) => setSeverityFilter(e.target.value)}
                className="px-3 py-2 bg-white/5 border border-white/10 rounded text-white text-sm"
              >
                <option value="">All Severity</option>
                <option value="INFO">Info</option>
                <option value="WARNING">Warning</option>
                <option value="ERROR">Error</option>
                <option value="CRITICAL">Critical</option>
              </select>
              <Button
                onClick={() => loadDashboardData()}
                variant="ghost"
                className="gap-2"
              >
                <RefreshCw size={16} />
                Refresh
              </Button>
              <Button
                onClick={exportToPDF}
                className="bg-green-600 hover:bg-green-700 gap-2"
              >
                <Download size={16} />
                Export PDF
              </Button>
            </div>
          </Card>

          {/* Logs Count */}
          <div className="flex justify-between items-center text-sm text-gray-400">
            <span>Showing {filteredLogs.length} of {auditLogs.length} logs</span>
            <span>Last updated: {new Date().toLocaleTimeString()}</span>
          </div>

          {/* Logs Table */}
          <Card>
            {loading ? (
              <p className="text-gray-400">Loading audit logs...</p>
            ) : filteredLogs.length === 0 ? (
              <p className="text-gray-400">No audit logs found matching your criteria</p>
            ) : (
              <div className="overflow-x-auto max-h-[500px] overflow-y-auto">
                <table className="w-full text-sm">
                  <thead className="sticky top-0 bg-gray-900">
                    <tr className="border-b border-white/6 text-gray-400">
                      <th className="px-4 py-3 text-left font-semibold">Time</th>
                      <th className="px-4 py-3 text-left font-semibold">User</th>
                      <th className="px-4 py-3 text-left font-semibold">Role</th>
                      <th className="px-4 py-3 text-left font-semibold">Action</th>
                      <th className="px-4 py-3 text-left font-semibold">Severity</th>
                      <th className="px-4 py-3 text-left font-semibold">Status</th>
                      <th className="px-4 py-3 text-left font-semibold">Details</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-white/6">
                    {filteredLogs.map(log => (
                      <tr key={log.id} className="hover:bg-white/2">
                        <td className="px-4 py-3 text-gray-400 text-xs whitespace-nowrap">
                          {new Date(log.created_at || log.timestamp || '').toLocaleString()}
                        </td>
                        <td className="px-4 py-3 font-semibold text-white text-xs">
                          {log.user_email || log.actor_name || 'System'}
                        </td>
                        <td className="px-4 py-3">
                          <span className="px-2 py-1 bg-blue-500/20 text-blue-300 text-xs rounded">
                            {log.user_role || log.actor_role || 'N/A'}
                          </span>
                        </td>
                        <td className="px-4 py-3">
                          <span className={`px-2 py-1 text-xs rounded ${
                            log.action?.includes('SUCCESS') || log.action === 'CREATE' ? 'bg-green-500/20 text-green-400' :
                            log.action?.includes('FAILED') || log.action?.includes('DENIED') ? 'bg-red-500/20 text-red-400' :
                            log.action === 'UPDATE' ? 'bg-yellow-500/20 text-yellow-400' :
                            log.action?.includes('ENCRYPT') || log.action?.includes('DECRYPT') ? 'bg-purple-500/20 text-purple-400' :
                            'bg-gray-500/20 text-gray-400'
                          }`}>
                            {log.action}
                          </span>
                        </td>
                        <td className="px-4 py-3">
                          <span className={`px-2 py-1 text-xs rounded ${
                            (log.details?.severity || log.severity) === 'CRITICAL' ? 'bg-red-500/20 text-red-400' :
                            (log.details?.severity || log.severity) === 'ERROR' ? 'bg-orange-500/20 text-orange-400' :
                            (log.details?.severity || log.severity) === 'WARNING' ? 'bg-yellow-500/20 text-yellow-400' :
                            'bg-gray-500/20 text-gray-400'
                          }`}>
                            {log.details?.severity || log.severity || 'INFO'}
                          </span>
                        </td>
                        <td className="px-4 py-3">
                          <span className={`px-2 py-1 text-xs rounded ${
                            log.status === 'success' ? 'bg-green-500/20 text-green-400' :
                            log.status === 'failed' ? 'bg-red-500/20 text-red-400' :
                            'bg-gray-500/20 text-gray-400'
                          }`}>
                            {log.status || 'N/A'}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-gray-400 text-xs max-w-[200px] truncate">
                          {JSON.stringify(log.details || log.entity_details || {}).substring(0, 50)}...
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </Card>
        </div>
      )}

      {/* Footer Info */}
      <Card className="bg-blue-500/5 border border-blue-500/20">
        <p className="text-xs text-gray-400">
          Dashboard is automatically updated every 30 seconds. All data shown is real-time and reflects current system state.
          For security, only administrators have access to this dashboard and all actions are logged in the audit trail.
        </p>
      </Card>
    </div>
  )
}

export default AdminDashboard
